import { StyleSheet } from 'react-native';

export function getStyles(isDarkMode) {
  return StyleSheet.create({
    flexContainer: {
      flex: 1,
      backgroundColor: isDarkMode ? '#121212' : '#FFF',
    },
    containerSuperior: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
      marginBottom: 16,
      paddingBottom: 0,
      paddingTop: 0,
      marginBottom: 0,

      backgroundColor: isDarkMode ? '#121212' : '#FFF',
    },
    detailsTopContainer: {
      padding: 5,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDarkMode ? '#121212' : '#FFF',
    },
    container: {
      flex: 1,
      padding: 20,
      backgroundColor: isDarkMode ? '#121212' : '#FFF',
    },
    scrollViewContainer: {
      flexGrow: 1,
      justifyContent: 'flex-start',
      alignItems: 'stretch',
      backgroundColor: isDarkMode ? '#121212' : '#FFF',
    },
    text: {
      color: isDarkMode ? 'white' : 'black',
      fontSize: 18,
    },
    button: {
      backgroundColor: isDarkMode ? '#444' : '#007bff',
      padding: 12,
      borderRadius: 8,
      alignItems: 'center',
      marginTop: 16,
      marginBottom: 30,
    },
    copyAddressButton: {
      alignSelf: 'flex-start',
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: isDarkMode ? '#60A5FA' : '#3B82F6',
      backgroundColor: isDarkMode ? 'rgba(59, 130, 246, 0.15)' : 'rgba(59, 130, 246, 0.08)',
      marginBottom: 10,
    },
    copyAddressButtonText: {
      color: isDarkMode ? '#93C5FD' : '#1D4ED8',
      fontWeight: '600',
      fontSize: 13,
    },
    addButton: {
      padding: 10,
      backgroundColor: '#007BFF',
      color: 'white',
      fontSize: 16,
      borderRadius: 5,
      textAlign: 'center',
      margin: 10,
    },
    buttonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: 'bold',
    },
    item: {
      padding: 10,
      fontSize: 18,
      height: 44,
      backgroundColor: isDarkMode ? '#333' : '#FFF',
    },
    title: {
      fontSize: 24,
      fontWeight: 'bold',
      color: isDarkMode ? 'white' : 'black',
      padding: 10,
      textAlign: 'center',
    },
    contentContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingBottom: 30,
      backgroundColor: isDarkMode ? '#121212' : '#FFF',
    },
    formContentContainer: {
      paddingHorizontal: 16,
      paddingBottom: 48,
      width: '100%',
    },
    label: {
      color: isDarkMode ? '#fff' : '#333',
      fontSize: 16,
      fontWeight: 'bold',
      marginBottom: 5,
    },
    scrollView: {
      flex: 1,
      paddingHorizontal: 10,
      backgroundColor: isDarkMode ? '#121212' : '#FFF',
    },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 15,
    },
    inputGroup: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      marginRight: 10,
    },
    input3: {
      flex: 1,
      height: 40,
      borderColor: '#ccc',
      borderWidth: 1,
      borderRadius: 5,
      paddingHorizontal: 10,
      marginRight: 10,
      backgroundColor: isDarkMode ? '#444' : '#fff',
      color: isDarkMode ? 'white' : 'black'
    },
    input: {
      marginBottom: 15,
      paddingHorizontal: 10,
      paddingVertical: 15,
      borderWidth: 1,
      borderColor: isDarkMode ? '#555' : '#ccc',
      backgroundColor: isDarkMode ? '#333' : '#fff',
      color: isDarkMode ? '#fff' : '#333',
      borderRadius: 5,
      fontSize: 16,
      width: '100%',
      alignSelf: 'center',
      height: 50,
      marginVertical: 12,
    },
    inputVelocidad: {
      width: '40%',
      marginBottom: 15,
      paddingHorizontal: 10,
      paddingVertical: 15,
      borderWidth: 1,
      borderColor: isDarkMode ? '#555' : '#ccc',
      backgroundColor: isDarkMode ? '#333' : '#fff',
      color: isDarkMode ? '#fff' : '#333',
      borderRadius: 5,
      fontSize: 16,
      alignSelf: 'center',
      height: 50,
      marginVertical: 12,
    },
    input2: {
      marginBottom: 15,
      paddingHorizontal: 10,
      paddingVertical: 15,
      borderWidth: 1,
      borderColor: isDarkMode ? '#555' : '#ccc',
      backgroundColor: isDarkMode ? '#333' : '#fff',
      color: isDarkMode ? '#fff' : '#333',
      borderRadius: 5,
      fontSize: 16,
      width: '15%',
      alignSelf: 'center',
      height: 50,
      marginVertical: 12,
      marginHorizontal: 10,
    },
    inputContainer: {
      marginBottom: 20,
      backgroundColor: isDarkMode ? '#121212' : '#FFF',
    },
    detailsContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
    },
    icon: {
      marginRight: 8,
      color: isDarkMode ? '#fff' : '#333',
    },
    itemContainer: {
      backgroundColor: isDarkMode ? '#333' : '#fff',
      padding: 16,
      marginBottom: 16,
      borderRadius: 8,
      marginBottom: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    addButton: {
      backgroundColor: '#5cb85c',
      padding: 10,
      borderRadius: 5,
      marginBottom: 10,
      alignSelf: 'center',
    },
    itemName: {
      fontSize: 20,
      fontWeight: 'bold',
      color: isDarkMode ? '#fff' : '#333',
    },
    itemDetails: {
      fontSize: 14,
      color: isDarkMode ? '#fff' : '#333',
    },
    buttonContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 20,
      width: '100%',
    },
    buttonContainer2: {
      flexDirection: 'column',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 10,
    },
    editButton: {
      backgroundColor: '#517fa4',
      padding: 10,
      borderRadius: 5,
      shadowColor: '#517fa4',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 3,
    },
    deleteButton: {
      backgroundColor: '#fa8072',
      padding: 10,
      borderRadius: 5,
      shadowColor: '#fa8072',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 3,
    },
    botonEditar: {
      backgroundColor: '#93CAED',
      padding: 10,
      borderRadius: 5,
      shadowColor: '#93CAED',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 3,
    },
    infoText: {
      color: isDarkMode ? '#fff' : '#333',
      fontSize: 15,
      padding: 0,
    },
    pickerContainer: {
      borderWidth: 1,
      borderColor: isDarkMode ? '#555' : '#ccc',
      borderRadius: 5,
      marginBottom: 15,
      overflow: 'hidden',
    },
    pickerStyle: {
      width: '100%',
      height: 50,
      color: isDarkMode ? 'white' : 'black',
      backgroundColor: isDarkMode ? '#333' : '#fff',
    },
    darkPicker: {
      backgroundColor: '#666',
      color: 'white',
    },
    lightPicker: {
      backgroundColor: '#fff',
      color: 'black',
    },
    darkDropDownContainer: {
      backgroundColor: '#555',
    },
    lightDropDownContainer: {
      backgroundColor: '#f8f8f8',
    },
    darkText: {
      color: 'white',
    },
    lightText: {
      color: 'black',
    },
    darkPlaceholder: {
      color: '#ccc',
    },
    lightPlaceholder: {
      color: '#333',
    },
    safeArea: {
      flex: 1,
      backgroundColor: isDarkMode ? '#000' : '#fff',
    },
    titleContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      padding: 10,
      backgroundColor: isDarkMode ? '#1c1c1e' : '#f8f8f8',
      borderRadius: 8,
      marginVertical: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    listContainer: {
      paddingHorizontal: 10,
    },
    conexionItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 10,
      borderBottomWidth: 1,
      borderBottomColor: 'gray',
    },
    conexionText: {
      flex: 1,
    },
    card: {
      backgroundColor: isDarkMode ? '#1c1c1e' : '#fff',
      borderRadius: 10,
      padding: 15,
      marginVertical: 10,
      marginHorizontal: 15,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    cardContent: {
      marginBottom: 10,
    },
    cardTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: isDarkMode ? '#fff' : '#000',
    },
    cardDetail: {
      fontSize: 16,
      color: isDarkMode ? '#e5e5e5' : '#333',
    },
    statusButton: {
      padding: 15,
      margin: 10,
      backgroundColor: '#4a90e2',
      borderRadius: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 3,
    },
    statusButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    selectedStatusButton: {
      backgroundColor: '#34a853',
      borderColor: 'white',
      borderWidth: 1,
    },
    searchContainer: {
      padding: 10,
      backgroundColor: 'white',
    },
    searchInput: {
      height: 40,
      borderColor: 'gray',
      borderWidth: 1,
      paddingLeft: 10,
      borderRadius: 5,
      color: isDarkMode ? '#fff' : '#333',
    },
    innerCard: {
      marginVertical: 10,
      padding: 15,
      backgroundColor: isDarkMode ? '#424242' : '#f0f0f0',
      borderRadius: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 1.5,
      elevation: 4,
      borderWidth: isDarkMode ? 0 : 1,
      borderColor: '#ddd',
    },
    itemContent: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingRight: 10,
    },
    itemInfo: {
      flex: 1,
    },
    buttonsContainer: {
      flexDirection: 'column',
    },
    addCard: {
      backgroundColor: isDarkMode ? '#444' : '#eee',
      borderRadius: 8,
      padding: 10,
      marginHorizontal: 5,
      width: 160,
      height: 170,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 5,
    },
    addCardText: {
      color: isDarkMode ? '#fff' : '#000',
      fontSize: 18,
      fontWeight: 'bold',
    },
    sectionTitle: {
      fontSize: 22,
      fontWeight: 'bold',
      marginVertical: 16,
      color: isDarkMode ? '#BB86FC' : '#6200EE',
      textAlign: 'center',
    },
    routerDetails: {
      fontSize: 18,
      color: isDarkMode ? '#FFFFFF' : '#000000',
      marginBottom: 8,
    },
    notebox: {
      borderColor: isDarkMode ? '#555' : '#ccc',
      borderWidth: 1,
      paddingHorizontal: 10,
      marginTop: 10,
      borderRadius: 5,
      backgroundColor: isDarkMode ? '#333' : '#fff',
      color: isDarkMode ? '#fff' : '#333',
      fontSize: 16,
      minHeight: 50,
      textAlignVertical: 'top',
    },
    issueCard: {
      backgroundColor: isDarkMode ? '#424242' : '#f0f0f0',
      borderRadius: 8,
      padding: 15,
      marginVertical: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 1.5,
      elevation: 4,
      borderWidth: isDarkMode ? 0 : 1,
      borderColor: '#ddd',
    },
    inputTouchable: {
      marginBottom: 15,
      paddingHorizontal: 10,
      paddingVertical: 15,
      borderWidth: 1,
      borderColor: isDarkMode ? '#555' : '#ccc',
      backgroundColor: isDarkMode ? '#333' : '#fff',
      borderRadius: 5,
      fontSize: 16,
      width: '100%',
      alignSelf: 'center',
      height: 60,
      justifyContent: 'center',
    },
    inputText: {
      color: isDarkMode ? '#fff' : '#333',
      fontSize: 16,
    },
    flatList: {
      backgroundColor: isDarkMode ? '#121212' : '#FFF',
    },
    formWrapper: {
      width: '100%',
    },
    sectionCard: {
      backgroundColor: isDarkMode ? '#1F2937' : '#FFFFFF',
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: isDarkMode ? '#374151' : '#E5E7EB',
      shadowColor: '#000',
      shadowOpacity: isDarkMode ? 0.25 : 0.08,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: isDarkMode ? '#F9FAFB' : '#111827',
    },
    sectionBadge: {
      backgroundColor: isDarkMode ? 'rgba(59, 130, 246, 0.2)' : 'rgba(59, 130, 246, 0.08)',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
    },
    sectionBadgeText: {
      fontSize: 12,
      fontWeight: '600',
      color: isDarkMode ? '#93C5FD' : '#2563EB',
    },
    sectionHelper: {
      fontSize: 12,
      color: isDarkMode ? '#9CA3AF' : '#6B7280',
      marginTop: 10,
    },
    selectorButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 14,
      paddingVertical: 14,
      borderWidth: 1,
      borderColor: isDarkMode ? '#4B5563' : '#E5E7EB',
      borderRadius: 12,
      backgroundColor: isDarkMode ? '#111827' : '#F9FAFB',
    },
    selectorContent: {
      flex: 1,
      paddingRight: 12,
    },
    selectorLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: isDarkMode ? '#9CA3AF' : '#6B7280',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    selectorValue: {
      fontSize: 15,
      fontWeight: '600',
      color: isDarkMode ? '#F3F4F6' : '#111827',
      marginTop: 4,
    },
    selectorCaret: {
      fontSize: 18,
      color: isDarkMode ? '#93C5FD' : '#2563EB',
    },
    dropdownList: {
      maxHeight: 220,
      marginTop: 10,
      borderWidth: 1,
      borderColor: isDarkMode ? '#4B5563' : '#E5E7EB',
      borderRadius: 12,
      backgroundColor: isDarkMode ? '#111827' : '#FFFFFF',
      overflow: 'hidden',
    },
    dropdownItem: {
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: isDarkMode ? '#1F2937' : '#F3F4F6',
    },
    dropdownItemText: {
      color: isDarkMode ? '#E5E7EB' : '#1F2937',
      fontSize: 14,
      fontWeight: '500',
    },
    inputLarge: {
      minHeight: 70,
      marginTop: 8,
    },
    inTimeBackground: {
      backgroundColor: '#28a745',
    },
    nearDueBackground: {
      backgroundColor: '#ffc107',
    },
    overDueBackground: {
      backgroundColor: '#dc3545',
    },
    chartContainer: {
      marginTop: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    searchInput: {
      height: 40,
      borderColor: 'gray',
      borderWidth: 1,
      paddingLeft: 10,
      borderRadius: 5,
      marginBottom: 10,
      backgroundColor: isDarkMode ? '#444' : '#fff',
      color: isDarkMode ? 'white' : 'black',
    },
    primaryButton: {
      backgroundColor: '#2563EB',
      paddingVertical: 16,
      borderRadius: 14,
      alignItems: 'center',
      marginTop: 12,
      shadowColor: '#2563EB',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.25,
      shadowRadius: 10,
      elevation: 5,
    },
    primaryButtonDisabled: {
      backgroundColor: isDarkMode ? '#1F2937' : '#CBD5F5',
      shadowOpacity: 0,
    },
    primaryButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
    },
    clienteItem: {
      padding: 10,
      borderBottomWidth: 1,
      borderBottomColor: '#ccc',
    },
    clienteItemText: {
      fontSize: 16,
    },
    articuloItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 10,
      borderBottomWidth: 1,
      borderBottomColor: isDarkMode ? '#555' : '#ccc',
      backgroundColor: isDarkMode ? '#333' : '#fff',
    },
    articuloText: {
      color: isDarkMode ? '#fff' : '#333',
      fontSize: 16,
    },
    eliminarTexto: {
      color: isDarkMode ? '#ff4d4d' : '#d9534f',
      fontSize: 16,
      fontWeight: 'bold',
    },
    clienteItem: {
      padding: 10,
      borderBottomWidth: 1,
      borderBottomColor: isDarkMode ? '#555' : '#ccc',
      backgroundColor: isDarkMode ? '#333' : '#fff',
    },
    clienteItemText: {
      color: isDarkMode ? '#fff' : '#333',
      fontSize: 16,
    },
    darkMode: {
      backgroundColor: '#121212',
      color: '#fff',
    },
    lightMode: {
      backgroundColor: '#fff',
      color: '#333',
    },
    resultText: {
      fontSize: 16,
      color: isDarkMode ? '#fff' : '#333',
      marginBottom: 15,
    },
    availableText: {
      color: 'green',
      fontWeight: 'bold',
    },
    // Modern ConfiguracionScreen styles
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: isDarkMode ? '#374151' : '#E5E7EB',
    },
    connectionIdContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
    },
    connectionIdContent: {
      marginLeft: 12,
      flex: 1,
    },
    connectionIdLabel: {
      fontSize: 14,
      marginBottom: 4,
    },
    connectionIdValue: {
      fontSize: 16,
      fontWeight: '600',
    },
    clientInfoContainer: {
      gap: 16,
    },
    clientDetailRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingVertical: 8,
    },
    clientDetailContent: {
      marginLeft: 12,
      flex: 1,
    },
    clientDetailLabel: {
      fontSize: 14,
      marginBottom: 4,
    },
    clientDetailValue: {
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 20,
    },
    routerSelectionContainer: {
      gap: 12,
    },
    routerSelectorWrapper: {
      marginBottom: 8,
    },
    routerStatsContainer: {
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: isDarkMode ? '#374151' : '#E5E7EB',
    },
    routerStatItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    routerStatText: {
      fontSize: 14,
      fontWeight: '500',
    },
    // ConfiguracionFijarIP modern styles
    loadingContainer: {
      alignItems: 'center',
      padding: 20,
    },
    warningContainer: {
      alignItems: 'center',
      padding: 24,
    },
    warningTitle: {
      fontSize: 18,
      fontWeight: '600',
      marginTop: 12,
      marginBottom: 8,
      textAlign: 'center',
    },
    warningText: {
      fontSize: 14,
      textAlign: 'center',
      lineHeight: 20,
    },
    emptyContainer: {
      alignItems: 'center',
      padding: 24,
    },
    emptyTitle: {
      fontSize: 16,
      fontWeight: '600',
      marginTop: 12,
      marginBottom: 8,
      textAlign: 'center',
    },
    emptyText: {
      fontSize: 14,
      textAlign: 'center',
      lineHeight: 20,
    },
    headerContent: {
      marginLeft: 12,
      flex: 1,
    },
    subtitle: {
      fontSize: 14,
      marginTop: 2,
    },
    leasesContainer: {
      gap: 12,
    },
    leaseCard: {
      borderRadius: 8,
      borderWidth: 1,
      padding: 16,
      marginBottom: 16,
    },
    leaseHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    leaseInfo: {
      flex: 1,
      marginLeft: 12,
    },
    leaseTitle: {
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 2,
    },
    leaseSubtitle: {
      fontSize: 12,
    },
    leaseDetails: {
      gap: 8,
    },
    leaseDetailItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    leaseDetailText: {
      fontSize: 12,
    },
    connectionInfoContainer: {
      gap: 16,
    },
    connectionDetailRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingVertical: 8,
    },
    connectionDetailContent: {
      marginLeft: 12,
      flex: 1,
    },
    connectionDetailLabel: {
      fontSize: 14,
      marginBottom: 4,
    },
    connectionDetailValue: {
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 20,
    },
    configOptionsContainer: {
      gap: 12,
    },
    configOption: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      marginBottom: 16,
      borderRadius: 8,
      borderWidth: 1,
    },
    configOptionContent: {
      flex: 1,
      marginLeft: 16,
    },
    configOptionTitle: {
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 4,
    },
    configOptionSubtitle: {
      fontSize: 14,
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
      gap: 12,
    },
    modalDeviceInfo: {
      backgroundColor: isDarkMode ? '#374151' : '#F3F4F6',
      padding: 12,
      borderRadius: 8,
      marginBottom: 16,
    },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 12,
      borderRadius: 6,
      borderWidth: 1,
      marginBottom: 12,
      gap: 8,
    },
    errorBannerText: {
      fontSize: 14,
      flex: 1,
    },
    // Information section styles
    infoSectionContainer: {
      gap: 16,
    },
    infoItem: {
      padding: 16,
      marginBottom: 16,
      borderRadius: 8,
      borderWidth: 1,
    },
    infoItemHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
      gap: 12,
    },
    infoItemTitle: {
      fontSize: 16,
      fontWeight: '600',
    },
    infoItemDescription: {
      fontSize: 14,
      lineHeight: 20,
    },
    recommendationBox: {
      flexDirection: 'row',
      padding: 16,
      marginBottom: 16,
      borderRadius: 8,
      borderWidth: 1,
      alignItems: 'flex-start',
      gap: 12,
    },
    recommendationContent: {
      flex: 1,
    },
    recommendationTitle: {
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 6,
    },
    recommendationText: {
      fontSize: 14,
      lineHeight: 20,
    },
    // ConfiguracionScreenRedes styles
    routerInfoContainer: {
      gap: 12,
    },
    routerInfoCard: {
      padding: 16,
      marginBottom: 16,
      borderRadius: 8,
      borderWidth: 1,
    },
    routerInfoHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    routerInfoContent: {
      marginLeft: 12,
      flex: 1,
    },
    routerInfoTitle: {
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 2,
    },
    routerInfoSubtitle: {
      fontSize: 12,
    },
    routerInfoDescription: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: isDarkMode ? '#4B5563' : '#E5E7EB',
    },
    routerInfoDescText: {
      fontSize: 14,
      flex: 1,
      lineHeight: 18,
    },
    networkSelectorContainer: {
      minHeight: 120,
    },
    // ConfiguracionScreenIp styles
    networkRouterContainer: {
      gap: 16,
    },
    networkRouterDetailRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingVertical: 8,
    },
    networkRouterDetailContent: {
      marginLeft: 12,
      flex: 1,
    },
    networkRouterDetailLabel: {
      fontSize: 14,
      marginBottom: 4,
    },
    networkRouterDetailValue: {
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 2,
    },
    networkRouterDetailSubValue: {
      fontSize: 12,
    },
    currentIpContainer: {
      gap: 12,
    },
    currentIpCard: {
      padding: 16,
      marginBottom: 16,
      borderRadius: 12,
      borderWidth: 2,
    },
    currentIpHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    currentIpInfo: {
      flex: 1,
      marginLeft: 12,
    },
    currentIpTitle: {
      fontSize: 20,
      fontWeight: '700',
      marginBottom: 2,
    },
    currentIpSubtitle: {
      fontSize: 14,
    },
    currentIpAction: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 6,
      borderWidth: 1,
      gap: 6,
    },
    currentIpActionText: {
      fontSize: 14,
      fontWeight: '600',
    },
    ipSelectorContainer: {
      minHeight: 150,
    },
    // ConfiguracionScreenPppoeVelocidad styles
    configSummaryContainer: {
      gap: 16,
    },
    summaryRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingVertical: 8,
    },
    summaryContent: {
      marginLeft: 12,
      flex: 1,
    },
    summaryLabel: {
      fontSize: 14,
      marginBottom: 4,
    },
    summaryValue: {
      fontSize: 16,
      fontWeight: '600',
    },
    pppoeConfigContainer: {
      gap: 16,
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    modernInput: {
      flex: 1,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 8,
      borderWidth: 1,
      fontSize: 16,
    },
    perfilContainer: {
      gap: 12,
    },
    perfilHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    perfilLabel: {
      fontSize: 14,
      fontWeight: '500',
    },
    disabledPppoeContainer: {
      alignItems: 'center',
      padding: 32,
      gap: 12,
    },
    disabledTitle: {
      fontSize: 18,
      fontWeight: '600',
      textAlign: 'center',
    },
    disabledText: {
      fontSize: 14,
      textAlign: 'center',
      lineHeight: 20,
    },
    speedLimitsContainer: {
      padding: 4,
    },
    notesContainer: {
      gap: 12,
    },
    modernNotebox: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 8,
      borderWidth: 1,
      fontSize: 16,
      minHeight: 100,
      textAlignVertical: 'top',
    },
    saveButtonContainer: {
      paddingHorizontal: 20,
      paddingVertical: 16,
    },
    modernSaveButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 16,
      paddingHorizontal: 24,
      borderRadius: 12,
      borderWidth: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 6,
    },
    saveButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: '#FFFFFF',
    },
  });
}
