// UsuarioDetalleStyles.js
import { StyleSheet } from 'react-native';

export const getStyles = (isDarkMode, isPermissionsVisible) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: isDarkMode ? '#0F0F0F' : '#F8F9FA',
            paddingHorizontal: 16,
        },
        header: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginVertical: 24,
            paddingHorizontal: 4,
        },
        title: {
            fontSize: 28,
            fontWeight: '700',
            color: isDarkMode ? '#FFFFFF' : '#1A1A1A',
            letterSpacing: 0.5,
        },
        detailCard: {
            backgroundColor: isDarkMode ? '#1C1C1E' : '#FFFFFF',
            borderRadius: 16,
            padding: 20,
            marginVertical: 12,
            shadowColor: isDarkMode ? '#000' : '#000',
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: isDarkMode ? 0.3 : 0.1,
            shadowRadius: 8,
            elevation: 4,
            borderWidth: isDarkMode ? 1 : 0,
            borderColor: isDarkMode ? '#2C2C2E' : 'transparent',
        },
        detailText: {
            fontSize: 16,
            color: isDarkMode ? '#E5E5E7' : '#48484A',
            marginBottom: 12,
            lineHeight: 22,
        },
        buttonRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginVertical: 16,
            gap: 12,
        },
        button: (color) => ({
            backgroundColor: color,
            borderRadius: 12,
            paddingVertical: 14,
            paddingHorizontal: 20,
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
            flexDirection: 'row',
            shadowColor: color,
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.2,
            shadowRadius: 4,
            elevation: 3,
        }),
        buttonText: {
            color: '#FFFFFF',
            fontSize: 16,
            fontWeight: '600',
            letterSpacing: 0.3,
        },
        modalContainer: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: 'rgba(0, 0, 0, 0.6)',
        },
        modalContent: {
            width: '85%',
            backgroundColor: isDarkMode ? '#1C1C1E' : '#FFFFFF',
            padding: 24,
            borderRadius: 20,
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 10,
            },
            shadowOpacity: 0.3,
            shadowRadius: 20,
            elevation: 10,
        },
        modalTitle: {
            fontSize: 22,
            fontWeight: '700',
            marginBottom: 20,
            color: isDarkMode ? '#FFFFFF' : '#1A1A1A',
            textAlign: 'center',
            letterSpacing: 0.3,
        },
        inputContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            marginBottom: 16,
        },
        input: {
            flex: 1,
            backgroundColor: isDarkMode ? '#2C2C2E' : '#F2F2F7',
            padding: 14,
            borderRadius: 12,
            color: isDarkMode ? '#FFFFFF' : '#1A1A1A',
            fontSize: 16,
            borderWidth: 1,
            borderColor: isDarkMode ? '#3A3A3C' : '#E5E5EA',
        },
        togglePasswordButton: {
            marginLeft: 12,
            padding: 4,
        },
        togglePasswordText: {
            fontSize: 20,
            color: isDarkMode ? '#FFFFFF' : '#1A1A1A',
        },
        modalButtonRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginTop: 20,
            gap: 12,
        },
        modalButton: (color) => ({
            backgroundColor: color,
            borderRadius: 12,
            paddingVertical: 14,
            paddingHorizontal: 20,
            flex: 1,
            alignItems: 'center',
            shadowColor: color,
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.2,
            shadowRadius: 4,
            elevation: 3,
        }),
        modalButtonText: {
            color: '#FFFFFF',
            fontSize: 16,
            fontWeight: '600',
            letterSpacing: 0.3,
        },
        card: {
            backgroundColor: isDarkMode ? '#1C1C1E' : '#FFFFFF',
            borderRadius: 16,
            marginVertical: 12,
            padding: 16,
            shadowColor: isDarkMode ? '#000' : '#000',
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: isDarkMode ? 0.3 : 0.08,
            shadowRadius: 8,
            elevation: 4,
            borderWidth: isDarkMode ? 1 : 0,
            borderColor: isDarkMode ? '#2C2C2E' : 'transparent',
        },
        cardHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingVertical: 4,
        },
        cardTitle: {
            fontSize: 20,
            fontWeight: '700',
            color: isDarkMode ? '#FFFFFF' : '#1A1A1A',
            letterSpacing: 0.3,
        },
        cardToggle: {
            fontSize: 18,
            color: isDarkMode ? '#007AFF' : '#007AFF',
            fontWeight: '600',
        },
        cardContent: {
            marginTop: 12,
            padding: 16,
            backgroundColor: isDarkMode ? '#2C2C2E' : '#F2F2F7',
            borderRadius: 12,
        },
        cardText: {
            color: isDarkMode ? '#FFFFFF' : '#1A1A1A',
            fontSize: 16,
            lineHeight: 22,
        },
        permissionCard: {
            backgroundColor: isDarkMode ? '#1C1C1E' : '#FFFFFF',
            borderRadius: 12,
            marginVertical: 8,
            padding: 12,
            shadowColor: isDarkMode ? '#000' : '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: isDarkMode ? 0.2 : 0.05,
            shadowRadius: 4,
            elevation: 2,
        },
        permissionHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: 12,
            backgroundColor: isDarkMode ? '#2C2C2E' : '#F8F9FA',
            borderRadius: 10,
        },
        permissionTitle: {
            flex: 1,
            fontSize: 18,
            fontWeight: '600',
            color: isDarkMode ? '#FFFFFF' : '#1A1A1A',
            letterSpacing: 0.2,
        },
        permissionContent: {
            marginTop: 12,
            padding: 12,
            backgroundColor: isDarkMode ? '#3A3A3C' : '#E5E5EA',
            borderRadius: 10,
        },
        subPermission: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingVertical: 10,
            paddingHorizontal: 14,
            marginVertical: 4,
            backgroundColor: isDarkMode ? '#2C2C2E' : '#F2F2F7',
            borderRadius: 8,
        },
        subPermissionText: {
            fontSize: 16,
            color: isDarkMode ? '#E5E5E7' : '#48484A',
            fontWeight: '500',
        },
        actionButton: {
            backgroundColor: '#34C759',
            padding: 14,
            marginVertical: 6,
            borderRadius: 12,
            alignItems: 'center',
            flexDirection: 'row',
            justifyContent: 'center',
            shadowColor: '#34C759',
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.2,
            shadowRadius: 4,
            elevation: 3,
        },
        actionButtonText: {
            color: '#FFFFFF',
            fontSize: 16,
            fontWeight: '600',
            letterSpacing: 0.3,
        },
        togglePermissionsButton: {
            marginTop: 16,
            backgroundColor: '#007AFF',
            padding: 14,
            borderRadius: 12,
            alignItems: 'center',
            shadowColor: '#007AFF',
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.2,
            shadowRadius: 4,
            elevation: 3,
        },
        togglePermissionsButtonText: {
            color: '#FFFFFF',
            fontSize: 16,
            fontWeight: '600',
            letterSpacing: 0.3,
        },
        eyes: {
            marginLeft: 12,
            fontSize: 20,
            color: isDarkMode ? '#FFD60A' : '#FF6B35',
        },
        toggleText: {
            fontSize: 20,
            color: isDarkMode ? '#007AFF' : '#007AFF',
            fontWeight: '600',
        },
        // Payment Methods Styles
        addPaymentButton: {
            backgroundColor: '#34C759',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            padding: 16,
            borderRadius: 12,
            marginBottom: 16,
            shadowColor: '#34C759',
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.2,
            shadowRadius: 4,
            elevation: 3,
        },
        addPaymentButtonText: {
            color: '#FFFFFF',
            fontSize: 16,
            fontWeight: '600',
            marginLeft: 8,
            letterSpacing: 0.3,
        },
        paymentMethodCard: {
            backgroundColor: isDarkMode ? '#2C2C2E' : '#F2F2F7',
            borderRadius: 12,
            padding: 16,
            marginBottom: 12,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            shadowColor: isDarkMode ? '#000' : '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: isDarkMode ? 0.2 : 0.05,
            shadowRadius: 4,
            elevation: 2,
        },
        paymentMethodInfo: {
            flex: 1,
        },
        paymentMethodName: {
            fontSize: 18,
            fontWeight: '600',
            color: isDarkMode ? '#FFFFFF' : '#1A1A1A',
            marginBottom: 6,
            letterSpacing: 0.2,
        },
        paymentMethodType: {
            fontSize: 14,
            color: isDarkMode ? '#AEAEB2' : '#6D6D70',
            marginBottom: 4,
            fontWeight: '500',
        },
        paymentMethodNumber: {
            fontSize: 14,
            color: isDarkMode ? '#AEAEB2' : '#6D6D70',
            marginBottom: 4,
            fontFamily: 'monospace',
        },
        paymentMethodStatus: {
            fontSize: 12,
            color: isDarkMode ? '#8E8E93' : '#8E8E93',
            fontWeight: '500',
        },
        paymentMethodActions: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
        },
        editButton: {
            padding: 10,
            borderRadius: 8,
            backgroundColor: isDarkMode ? '#1D4ED8' : '#DBEAFE',
        },
        deleteButton: {
            padding: 10,
            borderRadius: 8,
            backgroundColor: isDarkMode ? '#DC2626' : '#FEE2E2',
        },
        noPaymentMethodsText: {
            fontSize: 16,
            color: isDarkMode ? '#8E8E93' : '#8E8E93',
            textAlign: 'center',
            fontStyle: 'italic',
            marginTop: 24,
            letterSpacing: 0.2,
        },
        // Modal Payment Styles
        inputLabel: {
            fontSize: 16,
            color: isDarkMode ? '#FFFFFF' : '#1A1A1A',
            marginBottom: 12,
            fontWeight: '600',
            letterSpacing: 0.2,
        },
        radioContainer: {
            flexDirection: 'column',
            marginBottom: 18,
            gap: 8,
        },
        radioButton: {
            backgroundColor: isDarkMode ? '#3A3A3C' : '#E5E5EA',
            paddingHorizontal: 16,
            paddingVertical: 8,
            borderRadius: 20,
            alignItems: 'center',
            shadowColor: isDarkMode ? '#000' : '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: 0.1,
            shadowRadius: 2,
            elevation: 1,
        },
        radioButtonSelected: {
            backgroundColor: '#007AFF',
            shadowColor: '#007AFF',
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.3,
            shadowRadius: 4,
            elevation: 3,
        },
        radioButtonText: {
            color: isDarkMode ? '#FFFFFF' : '#1A1A1A',
            fontSize: 14,
            fontWeight: '600',
            letterSpacing: 0.2,
            textAlign: 'center',
        },
        switchContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginTop: 18,
            paddingVertical: 8,
        },
        switchLabel: {
            fontSize: 17,
            color: isDarkMode ? '#FFFFFF' : '#1A1A1A',
            fontWeight: '600',
            letterSpacing: 0.2,
        },
        scrollContainer: {
            maxHeight: 400,
        },
        // New styles for icons and visual elements
        detailItem: {
            flexDirection: 'row',
            alignItems: 'center',
            marginBottom: 12,
        },
        detailIcon: {
            marginRight: 12,
            width: 20,
            textAlign: 'center',
        },
        cardTitleContainer: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        cardIcon: {
            marginRight: 10,
        },
        buttonIcon: {
            marginRight: 8,
        },
        actionButtonIcon: {
            marginRight: 8,
        },
        addPaymentButtonIcon: {
            marginRight: 8,
        },
        toggleButton: {
            padding: 4,
            borderRadius: 4,
        },
        // Section styles for organized user data
        sectionHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            marginTop: 16,
            marginBottom: 12,
            paddingBottom: 8,
            borderBottomWidth: 1,
            borderBottomColor: isDarkMode ? '#3A3A3C' : '#E5E5EA',
        },
        sectionIcon: {
            marginRight: 8,
        },
        sectionTitle: {
            fontSize: 16,
            fontWeight: '700',
            color: isDarkMode ? '#007AFF' : '#007AFF',
            letterSpacing: 0.5,
        },
        // Styles for visitor/visited user indication
        titleContainer: {
            flex: 1,
        },
        viewingAsContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            marginTop: 4,
            paddingHorizontal: 8,
            paddingVertical: 2,
            backgroundColor: isDarkMode ? '#2C2C2E' : '#F2F2F7',
            borderRadius: 12,
            alignSelf: 'flex-start',
        },
        viewingAsText: {
            fontSize: 12,
            color: isDarkMode ? '#FF6B35' : '#FF6B35',
            marginLeft: 4,
            fontWeight: '500',
        },
        ownProfileContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            marginTop: 4,
            paddingHorizontal: 8,
            paddingVertical: 2,
            backgroundColor: isDarkMode ? '#1C3A28' : '#E8F5E8',
            borderRadius: 12,
            alignSelf: 'flex-start',
        },
        ownProfileText: {
            fontSize: 12,
            color: isDarkMode ? '#34C759' : '#34C759',
            marginLeft: 4,
            fontWeight: '600',
        },
        // Styles for disabled payment methods section
        cardHeaderDisabled: {
            opacity: 0.6,
        },
        cardTitleDisabled: {
            color: isDarkMode ? '#6D6D70' : '#8E8E93',
        },
        lockIcon: {
            marginLeft: 8,
        },
        cardContentDisabled: {
            alignItems: 'center',
            justifyContent: 'center',
            paddingVertical: 32,
            paddingHorizontal: 20,
        },
        privacyIcon: {
            marginBottom: 12,
        },
        privacyText: {
            fontSize: 18,
            fontWeight: '600',
            color: isDarkMode ? '#6D6D70' : '#8E8E93',
            textAlign: 'center',
            marginBottom: 8,
            letterSpacing: 0.2,
        },
        privacySubtext: {
            fontSize: 14,
            color: isDarkMode ? '#8E8E93' : '#8E8E93',
            textAlign: 'center',
            lineHeight: 20,
            letterSpacing: 0.1,
        },
    });
