import { StyleSheet } from 'react-native';

export const getStyles = (isDarkMode) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: isDarkMode ? '#0F172A' : '#F8FAFC',
        },
        scrollContent: {
            padding: 20,
            paddingBottom: 40,
            gap: 18,
        },
        sectionCard: {
            backgroundColor: isDarkMode ? '#1E293B' : '#FFFFFF',
            borderRadius: 16,
            padding: 18,
            borderWidth: 1,
            borderColor: isDarkMode ? '#334155' : '#E2E8F0',
            shadowColor: '#000',
            shadowOpacity: isDarkMode ? 0.35 : 0.08,
            shadowRadius: 10,
            shadowOffset: { width: 0, height: 4 },
            elevation: 4,
        },
        eyebrow: {
            fontSize: 12,
            textTransform: 'uppercase',
            letterSpacing: 0.6,
            color: isDarkMode ? '#94A3B8' : '#64748B',
            marginBottom: 4,
            fontWeight: '600',
        },
        headline: {
            fontSize: 20,
            fontWeight: '700',
            color: isDarkMode ? '#F8FAFC' : '#0F172A',
        },
        subhead: {
            fontSize: 14,
            fontWeight: '600',
            color: isDarkMode ? '#94A3B8' : '#475569',
            marginTop: 4,
        },
        sectionHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 12,
        },
        sectionTitle: {
            fontSize: 16,
            fontWeight: '700',
            color: isDarkMode ? '#E2E8F0' : '#0F172A',
        },
        badge: {
            paddingVertical: 4,
            paddingHorizontal: 10,
            borderRadius: 999,
            backgroundColor: isDarkMode ? 'rgba(96, 165, 250, 0.18)' : 'rgba(37, 99, 235, 0.12)',
        },
        badgeText: {
            fontSize: 12,
            fontWeight: '700',
            color: isDarkMode ? '#93C5FD' : '#1D4ED8',
        },
        pickerContainer: {
            borderWidth: 1,
            borderColor: isDarkMode ? '#475569' : '#CBD5F5',
            borderRadius: 12,
            overflow: 'hidden',
            backgroundColor: isDarkMode ? '#0F172A' : '#F8FAFF',
        },
        picker: {
            color: isDarkMode ? '#F1F5F9' : '#0F172A',
            height: 50,
        },
        helperText: {
            fontSize: 12,
            color: isDarkMode ? '#CBD5F5' : '#64748B',
            marginTop: 8,
        },
        input: {
            borderWidth: 1,
            borderColor: isDarkMode ? '#475569' : '#CBD5F5',
            borderRadius: 12,
            padding: 12,
            minHeight: 90,
            color: isDarkMode ? '#F8FAFC' : '#0F172A',
            backgroundColor: isDarkMode ? '#0F172A' : '#F8FAFF',
            textAlignVertical: 'top',
        },
        summaryRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            paddingVertical: 6,
            borderBottomWidth: 1,
            borderBottomColor: isDarkMode ? '#334155' : '#E2E8F0',
        },
        summaryLabel: {
            fontSize: 13,
            color: isDarkMode ? '#94A3B8' : '#64748B',
            fontWeight: '600',
        },
        summaryValue: {
            fontSize: 14,
            fontWeight: '700',
            color: isDarkMode ? '#F8FAFC' : '#0F172A',
        },
        primaryButton: {
            marginTop: 4,
            paddingVertical: 16,
            borderRadius: 14,
            alignItems: 'center',
            backgroundColor: '#2563EB',
            shadowColor: '#2563EB',
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.35,
            shadowRadius: 12,
            elevation: 6,
        },
        primaryButtonDisabled: {
            backgroundColor: isDarkMode ? '#1E293B' : '#CBD5F5',
            shadowOpacity: 0,
        },
        primaryButtonText: {
            color: '#FFFFFF',
            fontSize: 16,
            fontWeight: '700',
        },
    });
