import { StyleSheet } from 'react-native';

// Modern color palette
const colors = {
    // Primary Blues - Corporate & Professional
    primary: {
        50: '#EFF6FF',
        100: '#DBEAFE', 
        500: '#3B82F6',
        600: '#2563EB',
        700: '#1D4ED8',
        900: '#1E3A8A'
    },
    // Success Greens - Active connections
    success: {
        50: '#ECFDF5',
        100: '#D1FAE5',
        500: '#10B981',
        600: '#059669',
        700: '#047857'
    },
    // Warning Orange - Pending states
    warning: {
        50: '#FFFBEB',
        100: '#FEF3C7',
        500: '#F59E0B',
        600: '#D97706',
        700: '#B45309'
    },
    // Error Red - Critical actions
    error: {
        50: '#FEF2F2',
        100: '#FEE2E2',
        500: '#EF4444',
        600: '#DC2626',
        700: '#B91C1C'
    },
    // Neutral Grays - Text and backgrounds
    gray: {
        50: '#F8FAFC',
        100: '#F1F5F9',
        200: '#E2E8F0',
        300: '#CBD5E1',
        400: '#94A3B8',
        500: '#64748B',
        600: '#475569',
        700: '#334155',
        800: '#1E293B',
        900: '#0F172A'
    }
};

export const getStyles = (isDarkMode) => StyleSheet.create({
    containerSuperior: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: isDarkMode ? colors.gray[800] : colors.gray[50],
        borderBottomWidth: 1,
        borderBottomColor: isDarkMode ? colors.gray[700] : colors.gray[200],
    },
    buttonText: {
        color: isDarkMode ? colors.gray[100] : colors.gray[700],
        fontSize: 16,
        fontWeight: '600',
    },
    title: {
        fontSize: 20,
        fontWeight: '700',
        color: isDarkMode ? colors.gray[100] : colors.gray[900],
        textAlign: 'center',
        letterSpacing: -0.5,
    },
    container: {
        flex: 1,
        paddingHorizontal: 16,
        paddingVertical: 8,
        backgroundColor: isDarkMode ? colors.gray[900] : colors.gray[50],
    },
    card: {
        marginBottom: 16,
        marginHorizontal: 2,
        padding: 20,
        backgroundColor: isDarkMode ? colors.gray[800] : '#FFFFFF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: isDarkMode ? colors.gray[700] : colors.gray[200],
        shadowColor: isDarkMode ? '#000000' : colors.gray[900],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: isDarkMode ? 0.3 : 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: isDarkMode ? colors.gray[700] : colors.gray[200],
    },
    cardHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: isDarkMode ? colors.gray[100] : colors.gray[900],
        marginLeft: 8,
        letterSpacing: -0.3,
    },
    expandButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: isDarkMode ? colors.gray[700] : colors.gray[100],
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: isDarkMode ? colors.gray[600] : colors.gray[200],
        shadowColor: isDarkMode ? '#000000' : colors.gray[900],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: isDarkMode ? 0.3 : 0.1,
        shadowRadius: 3,
        elevation: 3,
    },
    expandButtonActive: {
        backgroundColor: colors.primary[600],
        borderColor: colors.primary[500],
        shadowColor: colors.primary[600],
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
    },
    compactInfo: {
        backgroundColor: isDarkMode ? colors.gray[700] : colors.gray[50],
        borderRadius: 8,
        padding: 12,
        marginBottom: 8,
    },
    cardSubtitle: {
        fontSize: 14,
        fontWeight: '500',
        color: isDarkMode ? colors.gray[400] : colors.gray[600],
        marginLeft: 8,
    },
    innerCard: {
        marginVertical: 8,
        padding: 16,
        backgroundColor: isDarkMode ? colors.gray[700] : colors.gray[50],
        borderRadius: 8,
        borderWidth: 1,
        borderColor: isDarkMode ? colors.gray[600] : colors.gray[200],
    },
    detailItem: {
        marginBottom: 16,
    },
    text: {
        fontSize: 15,
        lineHeight: 22,
        marginVertical: 3,
        color: isDarkMode ? colors.gray[200] : colors.gray[700],
        fontWeight: '400',
    },
    textBold: {
        fontSize: 15,
        lineHeight: 22,
        marginVertical: 3,
        color: isDarkMode ? colors.gray[100] : colors.gray[900],
        fontWeight: '600',
    },
    statusText: {
        fontSize: 15,
        fontWeight: '600',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        textAlign: 'center',
        overflow: 'hidden',
    },
    modalBackground: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    // modalContainer: {
    //     width: '80%',
    //     backgroundColor: isDarkMode ? '#333' : 'white',
    //     borderRadius: 10,
    //     padding: 20,
    //     alignItems: 'center',
    // },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 10,
        color: isDarkMode ? '#f8f9fa' : '#343a40',
        textAlign: 'center',
    },
    modalInput: {
        height: 100, // Incrementa la altura según sea necesario
        borderColor: isDarkMode ? '#777' : 'gray',
        borderWidth: 1,
        width: '100%',
        marginBottom: 20,
        paddingHorizontal: 10,
        borderRadius: 5,
        backgroundColor: isDarkMode ? '#555' : 'white',
        color: isDarkMode ? 'white' : 'black',
        textAlignVertical: 'top', // Asegura que el texto se alinee arriba
        fontSize: 16, // Ajusta el tamaño de fuente si es necesario
    },
    
    modalButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 20,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 10,
    },
    // Modern Button Hierarchy
    buttonPrimary: {
        backgroundColor: colors.primary[600],
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 6,
        shadowColor: colors.primary[600],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
        minHeight: 48,
    },
    buttonPrimaryText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: 0.5,
    },
    buttonSecondary: {
        backgroundColor: 'transparent',
        borderWidth: 2,
        borderColor: colors.primary[600],
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 6,
        minHeight: 48,
    },
    buttonSecondaryText: {
        color: colors.primary[600],
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: 0.5,
    },
    buttonSuccess: {
        backgroundColor: colors.success[600],
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 6,
        shadowColor: colors.success[600],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
        minHeight: 48,
    },
    buttonSuccessText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: 0.5,
    },
    buttonWarning: {
        backgroundColor: colors.warning[600],
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 6,
        shadowColor: colors.warning[600],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
        minHeight: 48,
    },
    buttonWarningText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: 0.5,
    },
    buttonDanger: {
        backgroundColor: colors.error[600],
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 6,
        shadowColor: colors.error[600],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
        minHeight: 48,
    },
    buttonDangerText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: 0.5,
    },
    // Action button for horizontal lists
    actionButton: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: colors.primary[600],
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 6,
        minWidth: 80,
        shadowColor: colors.primary[600],
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.15,
        shadowRadius: 2,
        elevation: 2,
    },
    actionButtonText: {
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: 14,
    },
    // Legacy support - will be replaced
    statusButton: {
        paddingVertical: 14,
        paddingHorizontal: 24,
        backgroundColor: colors.primary[600],
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 6,
        shadowColor: colors.primary[600],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
        minHeight: 48,
        textAlign: 'center',
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: 16,
        letterSpacing: 0.5,
    },
    deleteButton: {
        paddingVertical: 14,
        paddingHorizontal: 24,
        backgroundColor: colors.error[600],
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 6,
        shadowColor: colors.error[600],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
        minHeight: 48,
        textAlign: 'center',
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: 16,
        letterSpacing: 0.5,
    },
    // Modern Modal and Input Styles
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
    },
    modalView: {
        width: '90%',
        maxWidth: 400,
        backgroundColor: isDarkMode ? colors.gray[800] : '#FFFFFF',
        borderRadius: 16,
        padding: 24,
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 12,
        elevation: 8,
    },
    modalText: {
        fontSize: 18,
        fontWeight: '700',
        color: isDarkMode ? colors.gray[100] : colors.gray[900],
        textAlign: 'center',
        marginBottom: 20,
        letterSpacing: -0.3,
    },
    modalInput: {
        width: '100%',
        minHeight: 100,
        maxHeight: 150,
        borderColor: isDarkMode ? colors.gray[600] : colors.gray[300],
        borderWidth: 2,
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: isDarkMode ? colors.gray[700] : colors.gray[50],
        color: isDarkMode ? colors.gray[100] : colors.gray[900],
        fontSize: 16,
        textAlignVertical: 'top',
        lineHeight: 22,
        marginBottom: 20,
    },
    modalButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        gap: 12,
    },
    modalButton: {
        flex: 1,
        paddingVertical: 14,
        paddingHorizontal: 20,
        backgroundColor: colors.primary[600],
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: colors.primary[600],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
        minHeight: 48,
    },
    modalButtonSecondary: {
        flex: 1,
        paddingVertical: 14,
        paddingHorizontal: 20,
        backgroundColor: 'transparent',
        borderWidth: 2,
        borderColor: isDarkMode ? colors.gray[500] : colors.gray[400],
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 48,
    },
    modalButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: 0.5,
    },
    modalButtonSecondaryText: {
        color: isDarkMode ? colors.gray[300] : colors.gray[700],
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: 0.5,
    },
    // Modern limit and form components
    limitButton: {
        backgroundColor: colors.primary[600],
        paddingVertical: 14,
        paddingHorizontal: 20,
        marginVertical: 8,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: colors.primary[600],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 1,
        borderColor: isDarkMode ? colors.primary[500] : colors.primary[700],
    },
    limitButtonText: {
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: 16,
        textAlign: 'center',
        letterSpacing: 0.3,
    },
    inputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 12,
        paddingHorizontal: 4,
    },
    label: {
        fontSize: 16,
        fontWeight: '600',
        color: isDarkMode ? colors.gray[200] : colors.gray[700],
        marginRight: 12,
        minWidth: 80,
    },
    inputGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        gap: 8,
    },
    input: {
        flex: 1,
        height: 48,
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: isDarkMode ? colors.gray[600] : colors.gray[300],
        backgroundColor: isDarkMode ? colors.gray[700] : colors.gray[50],
        color: isDarkMode ? colors.gray[100] : colors.gray[900],
        fontSize: 16,
        fontWeight: '500',
    },
    unitPicker: {
        height: 48,
        width: 120,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: isDarkMode ? colors.gray[600] : colors.gray[300],
        backgroundColor: isDarkMode ? colors.gray[700] : colors.gray[50],
    },
    // Status indicators
    statusActive: {
        backgroundColor: colors.success[100],
        color: colors.success[700],
    },
    statusSuspended: {
        backgroundColor: colors.warning[100],
        color: colors.warning[700],
    },
    statusDisconnected: {
        backgroundColor: colors.error[100],
        color: colors.error[700],
    },
    statusPending: {
        backgroundColor: colors.gray[100],
        color: colors.gray[700],
    },
    // Pending issue indicator
    issueCard: {
        backgroundColor: colors.warning[50],
        borderColor: colors.warning[200],
        borderWidth: 2,
        borderRadius: 12,
        padding: 16,
        marginVertical: 8,
    },
    issueTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.warning[800],
        marginBottom: 8,
    },
    issueDescription: {
        fontSize: 14,
        color: colors.warning[700],
        lineHeight: 20,
    },
    // Loading and error states
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
    },
    loadingText: {
        fontSize: 16,
        color: isDarkMode ? colors.gray[400] : colors.gray[600],
        marginTop: 16,
        textAlign: 'center',
    },
    errorText: {
        fontSize: 16,
        color: colors.error[600],
        textAlign: 'center',
        fontWeight: '500',
        lineHeight: 22,
    },
    // Configuration Card Styles
    configSection: {
        marginVertical: 12,
    },
    configRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingVertical: 8,
        marginVertical: 4,
    },
    configDetails: {
        marginLeft: 12,
        flex: 1,
    },
    limitCard: {
        marginVertical: 6,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: isDarkMode ? colors.gray[600] : colors.gray[200],
        shadowColor: isDarkMode ? '#000000' : colors.gray[900],
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: isDarkMode ? 0.2 : 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    limitContent: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
    },
    limitDetails: {
        marginLeft: 12,
        flex: 1,
    },
    actionButtonsContainer: {
        flexDirection: 'row',
        marginTop: 20,
        gap: 12,
    },
    editButton: {
        backgroundColor: colors.primary[600],
    },
    removeButton: {
        backgroundColor: colors.error[600],
    },
    // Icon containers
    iconContainer: {
        width: 24,
        height: 24,
        justifyContent: 'center',
        alignItems: 'center',
    },
    
    // Installation Details Modern Component Styles
    sectionCard: {
        backgroundColor: isDarkMode ? colors.gray[800] : '#FFFFFF',
        borderRadius: 16,
        marginBottom: 16,
        padding: 20,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: isDarkMode ? 0.3 : 0.1,
        shadowRadius: 8,
        elevation: 6,
        borderWidth: 1,
        borderColor: isDarkMode ? colors.gray[700] : colors.gray[200],
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: isDarkMode ? colors.gray[700] : colors.gray[200],
        marginBottom: 16,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: isDarkMode ? colors.gray[100] : colors.gray[900],
        marginLeft: 12,
        letterSpacing: -0.3,
    },
    headerBadge: {
        backgroundColor: isDarkMode ? colors.primary[500] : colors.primary[600],
        borderRadius: 20,
        paddingHorizontal: 12,
        paddingVertical: 6,
        minWidth: 32,
        alignItems: 'center',
        justifyContent: 'center',
    },
    badgeText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '700',
    },
    sectionContent: {
        gap: 16,
    },
    installationCard: {
        backgroundColor: isDarkMode ? colors.gray[700] : colors.gray[50],
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: isDarkMode ? colors.gray[600] : colors.gray[200],
        marginBottom: 12,
    },
    installationHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    installationInfo: {
        flex: 1,
    },
    installationIdContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
    },
    installationId: {
        fontSize: 16,
        fontWeight: '700',
        color: isDarkMode ? colors.gray[100] : colors.gray[900],
        marginLeft: 8,
    },
    installationDate: {
        fontSize: 14,
        color: isDarkMode ? colors.gray[400] : colors.gray[600],
        fontWeight: '500',
    },
    installationDetails: {
        gap: 8,
        marginBottom: 16,
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    detailLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: isDarkMode ? colors.gray[300] : colors.gray[700],
        width: 80,
    },
    detailValue: {
        fontSize: 14,
        color: isDarkMode ? colors.gray[200] : colors.gray[600],
        flex: 1,
        fontWeight: '500',
    },
    installationActions: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 8,
    },
    actionButtonPrimary: {
        backgroundColor: colors.primary[600],
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        flex: 1,
        shadowColor: colors.primary[600],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    actionButtonSecondary: {
        backgroundColor: 'transparent',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        flex: 1,
        borderWidth: 1,
        borderColor: isDarkMode ? colors.gray[500] : colors.gray[400],
    },
    actionButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '600',
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 40,
        paddingHorizontal: 20,
    },
    emptyStateTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: isDarkMode ? colors.gray[300] : colors.gray[700],
        marginTop: 16,
        marginBottom: 8,
    },
    emptyStateSubtitle: {
        fontSize: 14,
        color: isDarkMode ? colors.gray[400] : colors.gray[600],
        textAlign: 'center',
        lineHeight: 20,
    },
    newInstallationButton: {
        backgroundColor: colors.success[600],
        paddingVertical: 16,
        paddingHorizontal: 24,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        marginTop: 8,
        shadowColor: colors.success[600],
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 4,
    },
    newInstallationButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
        letterSpacing: 0.3,
    },

    // Estilos para el indicador de alerta de instalaciones abiertas
    alertContainer: {
        backgroundColor: isDarkMode ? '#FEF3C7' : '#FFFBEB',
        borderLeftWidth: 4,
        borderLeftColor: '#F59E0B',
        borderRadius: 8,
        padding: 16,
        marginHorizontal: 4,
        marginBottom: 16,
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
        shadowColor: '#F59E0B',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    alertTextContainer: {
        flex: 1,
        gap: 4,
    },
    alertTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#92400E',
        lineHeight: 20,
    },
    alertMessage: {
        fontSize: 14,
        color: '#B45309',
        lineHeight: 18,
        fontWeight: '500',
    },
    alertButton: {
        backgroundColor: '#F59E0B',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 6,
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: 80,
        shadowColor: '#F59E0B',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    alertButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '600',
        letterSpacing: 0.3,
    },
    
    // Estilos para MetricsDashboard
    periodSelector: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: 16,
        backgroundColor: isDarkMode ? colors.gray[700] : colors.gray[100],
        borderRadius: 8,
        padding: 4,
    },
    periodButton: {
        flex: 1,
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 6,
        alignItems: 'center',
    },
    periodButtonActive: {
        backgroundColor: isDarkMode ? colors.primary[600] : colors.primary[500],
    },
    periodButtonText: {
        fontSize: 14,
        fontWeight: '600',
    },
    metricsGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    metricCard: {
        flex: 1,
        backgroundColor: isDarkMode ? colors.gray[700] : colors.gray[50],
        borderRadius: 8,
        padding: 12,
        marginHorizontal: 4,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: isDarkMode ? colors.gray[600] : colors.gray[200],
    },
    metricTitle: {
        fontSize: 12,
        fontWeight: '500',
        marginTop: 8,
        textAlign: 'center',
    },
    metricValue: {
        fontSize: 16,
        fontWeight: '700',
        marginTop: 4,
        textAlign: 'center',
    },
    metricSubtitle: {
        fontSize: 10,
        marginTop: 2,
        textAlign: 'center',
    },
    networkTrafficSection: {
        marginTop: 16,
        marginBottom: 16,
    },
    chartSection: {
        marginTop: 16,
        alignItems: 'center',
    },
    chartLabel: {
        fontSize: 12,
        marginTop: 8,
        textAlign: 'center',
    },
    metricsAdditionalInfo: {
        marginTop: 16,
        padding: 12,
        backgroundColor: isDarkMode ? colors.gray[700] : colors.gray[50],
        borderRadius: 8,
        borderWidth: 1,
        borderColor: isDarkMode ? colors.gray[600] : colors.gray[200],
    },
    metricsInfoTitle: {
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 8,
    },
    metricsInfoText: {
        fontSize: 12,
        marginBottom: 4,
    },
    metricsLoadingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 20,
    },
    metricsLoadingText: {
        marginLeft: 8,
        fontSize: 14,
    },
    metricsNoDataContainer: {
        alignItems: 'center',
        paddingVertical: 32,
    },
    metricsNoDataText: {
        fontSize: 14,
        marginTop: 12,
        textAlign: 'center',
    },
    metricsRetryButton: {
        marginTop: 12,
        paddingVertical: 8,
        paddingHorizontal: 16,
    },
    metricsRetryButtonText: {
        fontSize: 14,
        fontWeight: '600',
    },

    // Estilos para RealTimeConnections
    connectionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    currentConnectionItem: {
        // Estilo especial para la conexión actual
    },
    connectionId: {
        fontSize: 14,
        fontWeight: '600',
    },
    connectionIP: {
        fontSize: 12,
        marginTop: 2,
    },
    connectionSpeed: {
        fontSize: 14,
        fontWeight: 'bold',
    },
    connectionBytes: {
        fontSize: 11,
        marginTop: 2,
    },

    // Estilos mejorados para la tarjeta de detalles de conexión
    connectionDetailsContainer: {
        marginTop: 16,
    },
    connectionDetailRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        // Color del borde será aplicado dinámicamente
    },
    connectionDetailContent: {
        flex: 1,
        marginLeft: 12,
    },
    connectionDetailLabel: {
        fontSize: 13,
        fontWeight: '500',
        marginBottom: 4,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        // Color será aplicado dinámicamente
    },
    connectionDetailValue: {
        fontSize: 16,
        fontWeight: '600',
        lineHeight: 20,
        // Color será aplicado dinámicamente
    },
    statusContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    statusIndicator: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 8,
    },
    statusValue: {
        fontSize: 16,
        fontWeight: '600',
        lineHeight: 20,
        textTransform: 'capitalize',
    },

    // Estilos para la alerta de avería modernizada
    modernIssueCard: {
        borderLeftWidth: 4,
        borderLeftColor: '#F59E0B',
        borderRadius: 12,
        padding: 16,
        marginTop: 16,
        marginBottom: 8,
        // Color de fondo será aplicado dinámicamente
    },
    modernIssueHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    modernIssueTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#F59E0B',
        marginLeft: 8,
    },
    modernIssueDescription: {
        fontSize: 14,
        lineHeight: 20,
        marginBottom: 12,
        // Color será aplicado dinámicamente
    },
    modernIssueAction: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
    },
    modernIssueActionText: {
        fontSize: 13,
        fontWeight: '500',
        color: '#F59E0B',
        marginRight: 6,
    },

    // Container para los botones de acciones
    connectionActionsContainer: {
        marginTop: 20,
        paddingTop: 16,
        borderTopWidth: 1,
        // Color del borde será aplicado dinámicamente
    },
    
    // Grid responsivo para los botones
    connectionActionsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        gap: 8,
    },
    
    // Estilo base para botones en grid
    gridButton: {
        minWidth: '48%', // 2 columnas en pantallas pequeñas
        maxWidth: '48%',
        flex: 0,
    },

    // Estilos modernos para botones
    modernButtonSuccess: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#10B981',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 10,
        shadowColor: '#10B981',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
        gap: 8,
    },
    modernButtonWarning: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F59E0B',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 10,
        shadowColor: '#F59E0B',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
        gap: 8,
    },
    modernButtonDanger: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#EF4444',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 10,
        shadowColor: '#EF4444',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
        gap: 8,
    },
    modernButtonSecondary: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 10,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 1,
        gap: 8,
        // Colores serán aplicados dinámicamente
    },
    modernButtonText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#FFFFFF',
        letterSpacing: 0.3,
        textAlign: 'center',
        flexShrink: 1,
    },
    modernButtonSecondaryText: {
        fontSize: 15,
        fontWeight: '600',
        letterSpacing: 0.3,
        textAlign: 'center',
        flexShrink: 1,
        // Color será definido dinámicamente en el componente
    },

    // Estilos para la tarjeta de acciones modernizada
    modernActionsContainer: {
        marginTop: 16,
    },
    modernActionsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        gap: 12,
    },
    modernActionCard: {
        width: '48%', // 2 columnas
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
        borderWidth: 1,
        borderColor: isDarkMode => isDarkMode ? '#374151' : '#E5E7EB',
    },
    modernActionIcon: {
        width: 48,
        height: 48,
        borderRadius: 24,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 3,
        elevation: 3,
    },
    modernActionText: {
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: 4,
    },
    modernActionSubtext: {
        fontSize: 12,
        textAlign: 'center',
        opacity: 0.8,
    },

    // Estilos para componentes de instalación
    sectionCard: {
        marginBottom: 16,
        marginHorizontal: 2,
        padding: 20,
        backgroundColor: isDarkMode ? colors.gray[800] : '#FFFFFF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: isDarkMode ? colors.gray[700] : colors.gray[200],
        shadowColor: isDarkMode ? '#000000' : colors.gray[900],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: isDarkMode ? 0.3 : 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: isDarkMode ? colors.gray[700] : colors.gray[200],
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: isDarkMode ? colors.gray[100] : colors.gray[900],
        marginLeft: 8,
        letterSpacing: -0.3,
    },
    headerBadge: {
        backgroundColor: isDarkMode ? colors.gray[700] : colors.gray[100],
        borderRadius: 12,
        paddingHorizontal: 8,
        paddingVertical: 4,
        marginRight: 8,
    },
    badgeText: {
        fontSize: 12,
        fontWeight: '600',
        color: isDarkMode ? colors.gray[100] : colors.gray[900],
    },
    sectionContent: {
        gap: 16,
    },
    installationCard: {
        backgroundColor: isDarkMode ? colors.gray[700] : colors.gray[50],
        borderRadius: 8,
        padding: 16,
        borderWidth: 1,
        borderColor: isDarkMode ? colors.gray[600] : colors.gray[200],
    },
    installationHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    installationInfo: {
        flex: 1,
    },
    installationIdContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
    },
    installationId: {
        fontSize: 16,
        fontWeight: '600',
        color: isDarkMode ? colors.gray[100] : colors.gray[900],
        marginLeft: 8,
    },
    installationDate: {
        fontSize: 12,
        color: isDarkMode ? colors.gray[400] : colors.gray[600],
    },
    installationDetails: {
        marginBottom: 16,
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 6,
    },
    detailLabel: {
        fontSize: 14,
        fontWeight: '500',
        color: isDarkMode ? colors.gray[400] : colors.gray[600],
        marginLeft: 8,
        marginRight: 8,
        minWidth: 60,
    },
    detailValue: {
        fontSize: 14,
        fontWeight: '600',
        color: isDarkMode ? colors.gray[100] : colors.gray[900],
        flex: 1,
    },
    installationActions: {
        flexDirection: 'row',
        gap: 12,
    },
    actionButtonPrimary: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primary[600],
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        gap: 6,
    },
    actionButtonSecondary: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: isDarkMode ? colors.gray[600] : colors.gray[100],
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        gap: 6,
    },
    actionButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#FFFFFF',
    },

    // Estilos para detalles de conexión
    connectionDetailsContainer: {
        marginTop: 16,
        gap: 12,
    },
    connectionDetailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        borderBottomWidth: 1,
    },
    connectionDetailContent: {
        flex: 1,
        marginLeft: 12,
    },
    connectionDetailLabel: {
        fontSize: 14,
        fontWeight: '500',
        marginBottom: 2,
    },
    connectionDetailValue: {
        fontSize: 16,
        fontWeight: '600',
    },
    statusContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    statusIndicator: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    statusValue: {
        fontSize: 16,
        fontWeight: '600',
    },
   
});
