import { StyleSheet } from 'react-native';

export const getStyles = (isDarkMode: boolean) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: isDarkMode ? '#111827' : '#F9FAFB',
    },
    header: {
        backgroundColor: isDarkMode ? '#1F2937' : '#FFFFFF',
        paddingTop: 50,
        paddingBottom: 16,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: isDarkMode ? '#374151' : '#E5E7EB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
    },
    backButton: {
        marginBottom: 8,
    },
    backButtonText: {
        color: '#3B82F6',
        fontSize: 16,
        fontWeight: '600',
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: isDarkMode ? '#F9FAFB' : '#111827',
    },
    scrollView: {
        flex: 1,
        paddingHorizontal: 16,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: isDarkMode ? '#111827' : '#F9FAFB',
    },
    loadingText: {
        marginTop: 12,
        fontSize: 16,
        color: isDarkMode ? '#D1D5DB' : '#6B7280',
    },
    periodoContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 16,
        marginBottom: 16,
        backgroundColor: isDarkMode ? '#1F2937' : '#FFFFFF',
        borderRadius: 12,
        padding: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    periodoButton: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 8,
        borderRadius: 8,
        marginHorizontal: 2,
    },
    periodoButtonActive: {
        backgroundColor: isDarkMode ? '#3B82F6' : '#3B82F6',
    },
    periodoIcon: {
        fontSize: 20,
        marginBottom: 4,
    },
    periodoText: {
        fontSize: 12,
        fontWeight: '600',
        color: isDarkMode ? '#D1D5DB' : '#6B7280',
    },
    periodoTextActive: {
        color: '#FFFFFF',
    },
    estadisticasGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    estadisticaCard: {
        width: '48%',
        backgroundColor: isDarkMode ? '#1F2937' : '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        borderLeftWidth: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
        flexDirection: 'row',
        alignItems: 'center',
    },
    estadisticaIcono: {
        fontSize: 32,
        marginRight: 12,
    },
    estadisticaInfo: {
        flex: 1,
    },
    estadisticaTitulo: {
        fontSize: 12,
        color: isDarkMode ? '#9CA3AF' : '#6B7280',
        marginBottom: 4,
        fontWeight: '500',
    },
    estadisticaValor: {
        fontSize: 24,
        fontWeight: '700',
    },
    chartContainer: {
        backgroundColor: isDarkMode ? '#1F2937' : '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    chartTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: isDarkMode ? '#F9FAFB' : '#111827',
        marginBottom: 16,
    },
    chart: {
        borderRadius: 8,
        marginVertical: 8,
    },
    emptyChartContainer: {
        backgroundColor: isDarkMode ? '#1F2937' : '#FFFFFF',
        borderRadius: 12,
        padding: 40,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    emptyChartText: {
        fontSize: 16,
        color: isDarkMode ? '#9CA3AF' : '#6B7280',
        textAlign: 'center',
    },
    legendContainer: {
        marginTop: 16,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: isDarkMode ? '#374151' : '#E5E7EB',
    },
    legendRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: 12,
        flexWrap: 'wrap',
    },
    legendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        justifyContent: 'center',
        paddingVertical: 4,
        borderRadius: 999,
        marginHorizontal: 4,
        marginBottom: 8,
    },
    legendColor: {
        width: 16,
        height: 16,
        borderRadius: 8,
        marginRight: 8,
    },
    legendText: {
        fontSize: 12,
        fontWeight: '600',
        color: isDarkMode ? '#D1D5DB' : '#374151',
    },
    legendItemActive: {
        backgroundColor: isDarkMode ? 'rgba(59, 130, 246, 0.15)' : 'rgba(59, 130, 246, 0.08)',
    },
    legendItemInactive: {
        opacity: 0.6,
    },
    legendTextActive: {
        color: isDarkMode ? '#F9FAFB' : '#111827',
    },
    legendTextInactive: {
        color: isDarkMode ? '#6B7280' : '#9CA3AF',
    },
    navegadorFechas: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: isDarkMode ? '#1F2937' : '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    navegadorBoton: {
        backgroundColor: isDarkMode ? '#374151' : '#F3F4F6',
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    navegadorBotonDeshabilitado: {
        backgroundColor: isDarkMode ? '#1F2937' : '#E5E7EB',
        opacity: 0.5,
    },
    navegadorIcono: {
        fontSize: 18,
        color: isDarkMode ? '#F9FAFB' : '#111827',
        fontWeight: '700',
    },
    navegadorIconoDeshabilitado: {
        color: isDarkMode ? '#6B7280' : '#9CA3AF',
    },
    periodoActualContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 12,
    },
    periodoActualLabel: {
        fontSize: 11,
        color: isDarkMode ? '#9CA3AF' : '#6B7280',
        marginBottom: 4,
        fontWeight: '500',
    },
    periodoActualTexto: {
        fontSize: 16,
        fontWeight: '700',
        color: isDarkMode ? '#F9FAFB' : '#111827',
        textAlign: 'center',
    },
});
