import { StyleSheet } from 'react-native';

export const createStyles = (isDarkMode: boolean) => StyleSheet.create({
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        margin: 20,
        borderRadius: 16,
        maxHeight: '90%',
        width: '90%',
        backgroundColor: isDarkMode ? '#1F2937' : '#FFFFFF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 8,
        elevation: 8,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: isDarkMode ? '#374151' : '#E5E7EB',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '600',
        color: isDarkMode ? '#F9FAFB' : '#1F2937',
    },
    modalContent: {
        padding: 20,
    },
    inputGroup: {
        marginBottom: 16,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 8,
        color: isDarkMode ? '#D1D5DB' : '#374151',
    },
    textInput: {
        borderWidth: 1,
        borderRadius: 8,
        padding: 12,
        fontSize: 16,
        backgroundColor: isDarkMode ? '#374151' : '#F9FAFB',
        color: isDarkMode ? '#F9FAFB' : '#1F2937',
        borderColor: isDarkMode ? '#4B5563' : '#D1D5DB',
    },
    textAreaInput: {
        borderWidth: 1,
        borderRadius: 8,
        padding: 12,
        fontSize: 16,
        minHeight: 100,
        textAlignVertical: 'top',
        backgroundColor: isDarkMode ? '#374151' : '#F9FAFB',
        color: isDarkMode ? '#F9FAFB' : '#1F2937',
        borderColor: isDarkMode ? '#4B5563' : '#D1D5DB',
    },
    checkboxContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: isDarkMode ? '#4B5563' : '#E5E7EB',
        backgroundColor: isDarkMode ? '#374151' : '#F9FAFB',
        marginTop: 8,
    },
    checkboxLabel: {
        marginLeft: 8,
        fontSize: 14,
        fontWeight: '500',
        color: isDarkMode ? '#D1D5DB' : '#374151',
    },
    modalActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 12,
        padding: 20,
        borderTopWidth: 1,
        borderTopColor: isDarkMode ? '#374151' : '#E5E7EB',
    },
    modalButton: {
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 8,
        minWidth: 100,
        alignItems: 'center',
    },
    cancelButton: {
        borderWidth: 1,
        borderColor: isDarkMode ? '#4B5563' : '#D1D5DB',
    },
    saveButton: {
        backgroundColor: '#3B82F6',
    },
    cancelButtonText: {
        fontSize: 16,
        fontWeight: '500',
        color: isDarkMode ? '#9CA3AF' : '#6B7280',
    },
    saveButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
});
